### PR TITLE
Merge wild branch into main

### PR DESCRIPTION
**Pull request by davidlattimore**
Having a separate branch for wild seems to be causing confusion, so I've updated the old blog post to point to the specific commit that it used and will merge the wild-specific changes into main

### CODE REVIEW

**Comment by davidlattimore** [comment]
@marxin FYI

**Comment by marxin** [comment]
Cool, I welcome that.

**Comment by marxin** [comment]
@davidlattimore, would you welcome a change to the `run-benchmark` that will present the output in a markup format that could be placed directly into the Wild's README.md page?

**Comment by davidlattimore** [comment]
Sure, that'd be neat. Only if it's not too much trouble though and / or you think it'll be fun

**Comment by davidlattimore** [comment]
@marxin - although, it just occurred to me that the benchmarks run in this repository are for the whole build, whereas the benchmarks in the Wild readme are just running the linker.

**Comment by marxin** [comment]
Yep, to be honest, once you have added a collection of statistics, I would wait to add this.

In the future, we might want to incorporate something similar to https://github.com/gimli-rs/addr2line/blob/master/scripts/benchmark-plot.py, which processes JSON output from `hyperfine` and presents the data in a graphical form: https://github.com/gimli-rs/addr2line?tab=readme-ov-file#performance.

**Pull request merged**
