### PR TITLE
Modernize benchmarking

### PR DESCRIPTION
**Pull request by marxin**
There are various changes part of this PR:
- As we support debug info, we should measure it as it's the default for `cargo b`.
- `x86_64-unknown-linux-musl` is problematic as I don't have `musl-gcc` used for one system dependency; I would rather build a common `x86_64-unknown-linux-gnu` target where we'll only have glibc being dynamically linked against or binary
- `random-edit`: simplify by using `$RANDOM` and `include_str`
- `run-benchmark` - iterates all linkers (where `wild` needs to be coping to the current folder)

The output binary has the following size proportions:
```
❯ bloaty target/debug/warm-build-benchmark
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  65.5%   444Mi   0.0%       0    .debug_str
  13.3%  90.0Mi   0.0%       0    .debug_info
   4.6%  31.2Mi  70.8%  31.2Mi    .text
   4.4%  30.0Mi   0.0%       0    .debug_line
   4.0%  26.9Mi   0.0%       0    .strtab
   3.3%  22.3Mi   0.0%       0    .debug_ranges
   1.7%  11.3Mi   0.0%       0    .debug_loc
   0.7%  5.01Mi   0.0%       0    .debug_aranges
   0.6%  4.21Mi   0.0%       0    .symtab
   0.6%  3.78Mi   8.6%  3.78Mi    .eh_frame
   0.5%  3.11Mi   7.1%  3.11Mi    .rela.dyn
   0.3%  1.80Mi   4.1%  1.80Mi    .data
   0.2%  1.31Mi   3.0%  1.31Mi    .rodata
   0.2%  1.30Mi   2.9%  1.30Mi    .gcc_except_table
   0.2%  1.10Mi   2.5%  1.10Mi    .eh_frame_hdr
   0.1%   494Ki   1.1%   494Ki    .got
   0.1%   478Ki   0.0%       0    .debug_abbrev
   0.0%  3.25Ki   0.0%  2.60Ki    [23 Others]
   0.0%  2.62Ki   0.0%  2.62Ki    [ELF Section Headers]
   0.0%  2.51Ki   0.0%  2.51Ki    .dynsym
   0.0%  1.66Ki   0.0%  1.66Ki    .dynstr
 100.0%   678Mi 100.0%  44.1Mi    TOTAL
```

And the performance numbers are the following:
```
❯ ./run-benchmark 
Benchmark 1: ld.bfd
  Time (mean ± σ):      6.403 s ±  0.135 s    [User: 4.364 s, System: 2.039 s]
  Range (min … max):    6.215 s …  6.718 s    10 runs
 
628M	target/debug/warm-build-benchmark
Benchmark 1: ld.gold
  Time (mean ± σ):      4.170 s ±  0.108 s    [User: 3.864 s, System: 1.891 s]
  Range (min … max):    4.042 s …  4.340 s    10 runs
 
681M	target/debug/warm-build-benchmark
Benchmark 1: ld.lld
  Time (mean ± σ):      1.349 s ±  0.063 s    [User: 1.992 s, System: 1.532 s]
  Range (min … max):    1.261 s …  1.430 s    10 runs
 
683M	target/debug/warm-build-benchmark
Benchmark 1: mold
  Time (mean ± σ):     912.0 ms ±  40.8 ms    [User: 4031.7 ms, System: 3550.5 ms]
  Range (min … max):   853.7 ms … 967.3 ms    10 runs
 
709M	target/debug/warm-build-benchmark
Benchmark 1: /home/marxin/Programming/warm-build-benchmark/wild
  Time (mean ± σ):     996.4 ms ±  11.8 ms    [User: 2873.9 ms, System: 1614.7 ms]
  Range (min … max):   974.2 ms … 1012.2 ms    10 runs
 
679M	target/debug/warm-build-benchmark
```

It would be nice to update the `wild`'s README page once this gets merged.

### CODE REVIEW

**Comment by davidlattimore** [comment]
I made this repo originally for [this blog post](https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html). So in that regard having debug info turned off was deliberate, since regardless of which linker you're using, that saves a lot of time. It is the default for `cargo build`. Personally I think it shouldn't be. I'd be happier if cargo had three default profiles - release, fastbuild and debug with fastbuild being the default.

Regarding static linking, that was what worked well for that blog post, since it resulted in the fastest build and link times.

I agree that Wild's benchmarks should show link times for builds with debug info - but probably also still show builds without debug info in another column.

Another thing worth mentioning is that the benchmarks I've got in wild's README (which are pretty out-of-date) are just for running the linker, not for running a whole `cargo run`. The way I generated them was something like `WILD_SAVE_BASE=/tmp/wb1 RUSTFLAGS="-Clinker=clang -Clink-args=--ld-path=wild" cargo build`, then find the linker invocation that's of interest (usually the last one) in `/tmp/wb1` and run that. e.g. `hyperfine --warmup 2 '/tmp/wb1/10/run-with wild`.

I wonder if we should actually have a separate repository for linker benchmarking - or even just a "benchmarks" subdirectory in the main wild repo.

We could also consider using benchmarks that aren't based on this repo at all. I've increasingly been using linking of `librustc_driver.so`, which is the slowest link when building rustc.

**Comment by marxin** [comment]
> I agree that Wild's benchmarks should show link times for builds with debug info - but probably also still show builds without debug info in another column.

Works for me. Would be nice to have both (people will at least know how much complicated is the compilation w/ debug info).

> Another thing worth mentioning is that the benchmarks I've got in wild's README (which are pretty out-of-date) are just for running the linker, not for running a whole `cargo run`. The way I generated them was something like `WILD_SAVE_BASE=/tmp/wb1 RUSTFLAGS="-Clinker=clang -Clink-args=--ld-path=wild" cargo build`, then find the linker invocation that's of interest (usually the last one) in `/tmp/wb1` and run that. e.g. `hyperfine --warmup 2 '/tmp/wb1/10/run-with wild`.

Yeah, I've got the point. On the other hand, it's more comfortable to measure it with 'cargo build'. My expectation is that the cargo/rustc overhead would be rather small.

> I wonder if we should actually have a separate repository for linker benchmarking - or even just a "benchmarks" subdirectory in the main wild repo.

I like this current benchmark has a solid dependency graph based on Polars. It simulates the bigger Rust builds I guess. Don't have any strong opinion if this should be migrated to `Wild` :)

For now, we can probably leave this PR as is and we'll see if it's usable for benchmarking. What do you think?

**Comment by davidlattimore** [comment]
I created a new branch "wild" and will merge this PR into that. That'll mean that if anyone comes here from the blog post, it'll still match the post (static linking etc).

**Comment by marxin** [comment]
I welcome the selected approach ;)

**Pull request merged**
